spring:
  datasource:
    url: jdbc:mysql://localhost:3307/nimble?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc.time_zone: UTC
  flyway:
    enabled: true

# JWT Configuration
app:
  jwt:
    secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
    expiration: 86400000 # 24 hours
    refresh-expiration: 604800000 # 7 days

# External Services
external:
  authorizer:
    url: https://zsy6tx7aql.execute-api.saeast-1.amazonaws.com

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      authorizerService:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      authorizerService:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# SpringDoc Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    display-request-duration: true
    deep-linking: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
    doc-expansion: list
    show-extensions: true
    show-common-extensions: true

# Logging Configuration
logging:
  level:
    com.nimble.gateway: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE