spring:
  datasource:
    url: jdbc:mysql://localhost:3307/nimble?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc.time_zone: UTC
  flyway:
    enabled: true